export const imageLinks = {
    logo : "https://s3.us-east-1.amazonaws.com/cdn.betdevelopers.com/images/jmjs/5BeansCoffeeShop/logo.jpg",
    coffeeBag:"https://s3.us-east-1.amazonaws.com/cdn.betdevelopers.com/images/jmjs/5BeansCoffeeShop/coffee-bag.jpeg",
    flatwhite:"https://s3.us-east-1.amazonaws.com/cdn.betdevelopers.com/images/jmjs/5BeansCoffeeShop/FlatWhite.png",
    cookie :"https://s3.us-east-1.amazonaws.com/cdn.betdevelopers.com/images/jmjs/5BeansCoffeeShop/doubleChocolateCookie.jpeg",
    coconutBalls:"https://s3.us-east-1.amazonaws.com/cdn.betdevelopers.com/images/jmjs/5BeansCoffeeShop/coconutBalls.jpeg",
    pancake :"https://s3.us-east-1.amazonaws.com/cdn.betdevelopers.com/images/jmjs/5BeansCoffeeShop/pancake.jpeg",
    fondant:"https://s3.us-east-1.amazonaws.com/cdn.betdevelopers.com/images/jmjs/5BeansCoffeeShop/fondant.jpeg",
    lebaneseCoffee:"https://s3.us-east-1.amazonaws.com/cdn.betdevelopers.com/images/jmjs/5BeansCoffeeShop/lebaneseCoffee.jpeg",
    peanutButterJar:"https://s3.us-east-1.amazonaws.com/cdn.betdevelopers.com/images/jmjs/5BeansCoffeeShop/peanutbutterJar.jpeg",
    peanutButterJarSmall:"https://s3.us-east-1.amazonaws.com/cdn.betdevelopers.com/images/jmjs/5BeansCoffeeShop/peanutButterJarSmall.jpeg",
    milkshakeStrawberry:"https://s3.us-east-1.amazonaws.com/cdn.betdevelopers.com/images/jmjs/5BeansCoffeeShop/StrawberryMilkshake.png",
    datesBalls:"https://s3.us-east-1.amazonaws.com/cdn.betdevelopers.com/images/jmjs/5BeansCoffeeShop/dateBalls.jpeg",
    peanutButterBar:"https://s3.us-east-1.amazonaws.com/cdn.betdevelopers.com/images/jmjs/5BeansCoffeeShop/PeanutButterBar.png",
    footerFlatWhite: "https://s3.us-east-1.amazonaws.com/cdn.betdevelopers.com/images/jmjs/5BeansCoffeeShop/footerFlatWhite.png",
    logoHorizontal: "https://s3.us-east-1.amazonaws.com/cdn.betdevelopers.com/images/jmjs/5BeansCoffeeShop/logoHorizontal.jpg",
    aboutHeaderImg: "https://s3.us-east-1.amazonaws.com/cdn.betdevelopers.com/images/jmjs/5BeansCoffeeShop/AboutHeaderImg.avif",
    image2About: "https://s3.us-east-1.amazonaws.com/cdn.betdevelopers.com/images/jmjs/5BeansCoffeeShop/Image2About.avif",
    baristaAbout: "https://s3.us-east-1.amazonaws.com/cdn.betdevelopers.com/images/jmjs/5BeansCoffeeShop/BaristaAbout.avif",
    AboutIcedCoffee: "https://s3.us-east-1.amazonaws.com/cdn.betdevelopers.com/images/jmjs/5BeansCoffeeShop/AboutIcedCoffee.avif",
};